# Generated by Django 3.2.9 on 2022-01-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg_log', '0001_initial'),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_reg_log.profile'),
        ),
    ]
