# Generated by Django 3.2.9 on 2022-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg_log', '0001_initial'),
        ('shortener', '0002_urls_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='urls',
            name='user_profile',
            field=models.ManyToManyField(null=True, to='user_reg_log.Profile'),
        ),
    ]
